### ISSUE TITLE
Docker Gremlin Server

### ISSUE THREAD

**Issue by guyellis** [htaox/NEAT#2]
I'm using your Docker Gremlin Server image:
GitHub: https://github.com/htaox/NEAT/tree/master/docker-scripts/gremlin-server-3.0.0
Docker: https://hub.docker.com/r/htaox/gremlin-server/

Hitting this error, any ideas if this is PIBKAC?

```
$ docker run htaox/gremlin-server:3.0.0 
HOSTNAME=ca55ccd605ef
CA_CERTIFICATES_JAVA_VERSION=20140324
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
LANG=C.UTF-8
JAVA_VERSION=8u45
SHLVL=1
HOME=/root
JAVA_DEBIAN_VERSION=8u45-b14-2~bpo8+2
_=/usr/bin/env
IP=172.17.0.3
changing root password
starting sshd
starting gremlin-server
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/tinkerpop/gremlin/server/GremlinServer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

(Running on Ubuntu Desktop)

**Comment by htaox** [comment]
I updated the java version to 8u72 in the Dockerfile and rebuilt it in the Hub.  

I tested on Ubuntu 12.04LTS server without errors:

``` bash
CA_CERTIFICATES_JAVA_VERSION=20140324
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
LANG=C.UTF-8
JAVA_VERSION=8u72
SHLVL=1
HOME=/root
JAVA_DEBIAN_VERSION=8u72-b15-1~bpo8+1
_=/usr/bin/env
IP=172.17.0.202
changing root password
starting sshd
starting gremlin-server
log4j:WARN No appenders could be found for logger (io.netty.util.internal.loggin                                                                   g.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more in                                                                   fo.
3/24/16 7:09:22 PM =============================================================

-- Gauges ----------------------------------------------------------------------
org.apache.tinkerpop.gremlin.server.GremlinServer.sessions
             value = 0

-- Meters ----------------------------------------------------------------------
org.apache.tinkerpop.gremlin.server.GremlinServer.errors
             count = 0
         mean rate = 0.00 events/second
     1-minute rate = 0.00 events/second
     5-minute rate = 0.00 events/second
    15-minute rate = 0.00 events/second
org.apache.tinkerpop.gremlin.server.GremlinServer.op.control
             count = 0
         mean rate = 0.00 events/second
     1-minute rate = 0.00 events/second
     5-minute rate = 0.00 events/second
    15-minute rate = 0.00 events/second

-- Timers ----------------------------------------------------------------------
org.apache.tinkerpop.gremlin.server.GremlinServer.op.eval
             count = 0
         mean rate = 0.00 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 0.00 calls/second
               min = 0.00 milliseconds
               max = 0.00 milliseconds
              mean = 0.00 milliseconds
            stddev = 0.00 milliseconds
            median = 0.00 milliseconds
              75% <= 0.00 milliseconds
              95% <= 0.00 milliseconds
              98% <= 0.00 milliseconds
              99% <= 0.00 milliseconds
            99.9% <= 0.00 milliseconds
```

**Comment by guyellis** [comment]
That fixed it. Thanks!
